PSBT_INPUTS = "inputs"
PSBT_OUTPUTS = "outputs"
PSBT_UNKNOWN = "unknown"
PSBT_TX = "tx"
PSBT_TX_VIN = "vin"
PSBT_TX_VOUT = "vout"
PSBT_TX_ADDRESSES = "addresses"
PSBT_SCRIPTPUBKEY = "scriptPubKey"
PSBT_TYPE = "type"
PSBT_ADDRESS = "address"
PSBT_WITNESS_UTXO = "witness_utxo"
PSBT_NON_WITNESS_UTXO = "non_witness_utxo"
PSBT_BIP32_DERIVS = "bip32_derivs"
PSBT_BIP32_MASTER_FP = "master_fingerprint"
PSBT_BIP32_PATH = "path"

PSBT_WSH_TYPE = "witness_v0_scripthash"
